name: receipt_scanner
publish_to: 'none'
description: A Flutter app for receipt scanning with GPT-4o
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  image_picker: ^0.8.6
  url_launcher: ^6.1.7
  file_picker: ^5.2.4
  fl_chart: ^0.55.2
  universal_html: ^2.2.4
  amazon_cognito_identity_dart_2: ^3.0.1
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
